name: CD - Serveur Debian

on:
  workflow_run:
    workflows: ["CI - Test du site"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Déploiement vers /var/www/app
        run: |
          sudo mkdir -p /var/www/app
          sudo cp index.html /var/www/app/
